# Generated by Django 4.1.6 on 2023-02-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamplatform',
            old_name='wabsite',
            new_name='website',
        ),
    ]
