# Generated by Django 4.1.6 on 2023-03-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0010_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='streamplatform_id',
            new_name='platform',
        ),
    ]
